name: tf25
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - abseil-cpp=20210324.2=hd77b12b_0
  - absl-py=0.13.0=py38haa95532_0
  - aiohttp=3.7.4=py38h2bbff1b_1
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - astor=0.8.1=py38haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38haa95532_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blinker=1.4=py38haa95532_0
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2021.5.30=h5b45459_0
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py38haa244fe_0
  - cffi=1.14.6=py38h2bbff1b_0
  - chardet=3.0.4=py38haa95532_1003
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py38h2bbff1b_2
  - cryptography=3.4.7=py38h71e12ea_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cudnn=8.2.1=cuda11.3_0
  - cycler=0.10.0=py_2
  - cython=0.29.23=py38hd77b12b_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - flatbuffers=2.0.0=h6c2663c_0
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=h546665d_1
  - gast=0.4.0=py_0
  - giflib=5.2.1=h62dcd97_0
  - google-auth=1.32.1=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py38hc60d5dd_1
  - h5py=3.2.1=py38h3de5c98_0
  - hdf5=1.10.6=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=68.1=h6c2663c_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=haa95532_616
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.22.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jasper=2.0.14=h77af90b_2
  - jbig=2.1=h8d14728_2003
  - jedi=0.17.0=py38_0
  - jinja2=3.0.1=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras=2.4.3=0
  - keras-base=2.4.3=py_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py38hbd9d945_1
  - krb5=1.18.2=hc04afaa_0
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.71.1=h2a8f88b_1
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - liblapacke=3.9.0=5_hd5c7e75_netlib
  - libopencv=4.5.1=py38hf7032e7_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.14.0=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.3.0=h0c97f57_1
  - libwebp-base=1.2.0=h8ffe710_2
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=py38haa95532_0
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib=3.4.2=py38haa244fe_0
  - matplotlib-base=3.4.2=py38heae8d8c_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py38h2bbff1b_1
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.1=py38hf11a4ad_2
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py38h2bbff1b_2
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py38haa95532_0
  - numpy-base=1.20.2=py38hc2deb75_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py38haa244fe_0
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h8ffe710_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.2.5=py38hd77b12b_0
  - pandocfilters=1.4.3=py38haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py38h794f750_0
  - pip=21.1.3=py38haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - protobuf=3.14.0=py38hd77b12b_1
  - py-opencv=4.5.1=py38hc5df569_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38haa244fe_7
  - pyqt-impl=5.12.3=py38h885f38d_7
  - pyqt5-sip=4.19.18=py38h885f38d_7
  - pyqtchart=5.12=py38h885f38d_7
  - pyqtwebengine=5.12.1=py38h885f38d_7
  - pyreadline=2.1=py38_1
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.10=hdbf39b2_7
  - python-dateutil=2.8.1=py_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.4.1=py38h2bbff1b_1
  - pyzmq=20.0.0=py38hd77b12b_1
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=0.24.2=py38hf11a4ad_1
  - scikit-plot=0.3.7=py_1
  - scipy=1.6.2=py38h66253e8_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.36.0=h2bbff1b_0
  - tensorboard=2.5.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.5.0=gpu_py38h8e8c102_0
  - tensorflow-base=2.5.0=gpu_py38hb3da07e_0
  - tensorflow-estimator=2.5.0=pyh7b7c402_0
  - tensorflow-gpu=2.5.0=h17022bd_0
  - termcolor=1.1.0=py38haa95532_1
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tf_slim=1.1.0=pyhd3deb0d_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py38h294d835_1
  - tqdm=4.61.2=pyhd8ed1ab_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - yarl=1.6.3=py38h2bbff1b_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.5.0=h6255e5f_0
  - pip:
    - numpy==1.21.0
prefix: E:\anaconda3\envs\tf25
